# Generated by Django 4.0.2 on 2022-02-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField()),
                ('status', models.IntegerField(choices=[(1, 'new'), (2, 'old')])),
            ],
        ),
    ]
