# Generated by Django 4.0.2 on 2022-02-25 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='created_at',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='film',
            name='name',
            field=models.CharField(default=2, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='film',
            name='rate',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
